"""User-friendly labels, limits, and average values for the health data form."""

HEALTH_FIELD_INFO = {
    "sex": {
        "label": "Sex",
        "help": "Select Male or Female. If Male is selected, pregnancies will automatically be set to 0.",
        "average": None,
    },
    "pregnancies": {
        "label": "Pregnancies",
        "help": "0 = No / None. 1, 2, 3… = total number of pregnancies in lifetime.",
        "average": 0,
        "min": 0,
        "max": 17,
        "placeholder": "0",
        "unit": "",
    },
    "glucose": {
        "label": "Glucose",
        "help": "Fasting blood glucose level in mg/dL. Normal: 70–100. Prediabetes: 100–125. Diabetes: 140+.",
        "average": 95,
        "min": 0,
        "max": 300,
        "placeholder": "95",
        "unit": "mg/dL (fasting)",
    },
    "systolic": {
        "label": "Systolic Blood Pressure",
        "help": "The TOP number (when heart beats). Normal: below 120. High: 140 or above.",
        "average": 120,
        "min": 0,
        "max": 250,
        "placeholder": "120",
        "unit": "mm Hg",
    },
    "diastolic": {
        "label": "Diastolic Blood Pressure",
        "help": "The BOTTOM number (when heart rests). Normal: below 80. High: 90 or above.",
        "average": 80,
        "min": 0,
        "max": 150,
        "placeholder": "80",
        "unit": "mm Hg",
    },
    "skin_thickness": {
        "label": "Skin Thickness (triceps fold)",
        "help": "Skin fold thickness in mm. Average is about 20. Enter 0 if unknown.",
        "average": 20,
        "min": 0,
        "max": 100,
        "placeholder": "20",
        "unit": "mm",
    },
    "insulin": {
        "label": "Insulin Level",
        "help": "Blood insulin level. Average is about 80. Enter 0 if not tested.",
        "average": 80,
        "min": 0,
        "max": 900,
        "placeholder": "80",
        "unit": "mu U/ml",
    },
    "bmi": {
        "label": "BMI (Body Mass Index)",
        "help": "Weight relative to height. Normal: 18.5–24.9. Over 30 = obese.",
        "average": 25,
        "min": 10,
        "max": 70,
        "placeholder": "25",
        "unit": "kg/m²",
    },
    "diabetes_pedigree": {
        "label": "Family Diabetes History",
        "help": "0 = No — no close family member has diabetes. 1 = Yes — parent or sibling has diabetes.",
        "average": 0,
        "min": 0,
        "max": 1,
        "placeholder": "0",
        "unit": "0 or 1",
    },
    "age": {
        "label": "Age",
        "help": "Your age in years. Average in dataset is about 33.",
        "average": 33,
        "min": 1,
        "max": 120,
        "placeholder": "33",
        "unit": "years",
    },
}

# Low-risk example values for the "Fill healthy example" button.
HEALTHY_EXAMPLE = {
    "pregnancies": 0,
    "glucose": 85,
    "systolic": 110,
    "diastolic": 70,
    "skin_thickness": 20,
    "insulin": 60,
    "bmi": 22,
    "age": 28,
}
